export { ReactComponent as ArrowDown } from './Arrow_Down.svg';
export { ReactComponent as ArrowUp } from './Arrow_Up.svg';
export { ReactComponent as Book } from './Book.svg';
export { ReactComponent as Camera } from './Camera.svg';
export { ReactComponent as Cancel } from './Cancel.svg';
export { ReactComponent as Chart } from './Chart.svg';
export { ReactComponent as Checkmark } from './Checkmark.svg';
export { ReactComponent as ChevronDown } from './Chevron_Down.svg';
export { ReactComponent as User } from './User.svg';